config/routes.rb
Rails.application.routes.draw do
  resources :especialidades
  resources :especialidadades
  resources :mining_types
  get 'welcome/index'
  
  resources :cdzs
  
  root to: 'welcome#index'
  #root to: 'index.html'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cdz.rb
class Cdz < ApplicationRecord
    belongs_to :especialidade  #, optional: true
end

app/models/especialidade.rb
class Especialidade < ApplicationRecord
    has_many :cdzs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale
    
  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end
    
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/cdzs_controller.rb
class CdzsController < ApplicationController
  before_action :set_cdz, only: [ :show, :edit, :update, :destroy ]
  before_action :set_especialidade_options, only: [:new, :create, :edit, :update]

  # GET /cdzs or /cdzs.json
  def index
    @cdzs = Cdz.all
  end

  # GET /cdzs/1 or /cdzs/1.json
  def show
  end

  # GET /cdzs/new
  def new
    @cdz = Cdz.new
  end

  # GET /cdzs/1/edit
  def edit
  end

  # POST /cdzs or /cdzs.json
  def create
    @cdz = Cdz.new(cdz_params)

    respond_to do |format|
      if @cdz.save
        format.html { redirect_to cdz_url(@cdz), notice: "Cdz was successfully created." }
        format.json { render :show, status: :created, location: @cdz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cdz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cdzs/1 or /cdzs/1.json
  def update
    respond_to do |format|
      if @cdz.update(cdz_params)
        format.html { redirect_to cdz_url(@cdz), notice: "Cdz was successfully updated." }
        format.json { render :show, status: :ok, location: @cdz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cdz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cdzs/1 or /cdzs/1.json
  def destroy
    @cdz.destroy

    respond_to do |format|
      format.html { redirect_to cdzs_url, notice: "Cdz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_especialidade_options
      @especialidade_options = Especialidade.all.pluck(:tipo, :id)
    end
      
  
  
    # Use callbacks to share common setup or constraints between actions.
    def set_cdz
      @cdz = Cdz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cdz_params
      params.require(:cdz).permit(:nome, :costelação, :idade, :foto, :especialidade_id)
    end
end

app/controllers/especialidadades_controller.rb
class EspecialidadadesController < ApplicationController
  before_action :set_especialidadade, only: %i[ show edit update destroy ]

  # GET /especialidadades or /especialidadades.json
  def index
    @especialidadades = Especialidadade.all
  end

  # GET /especialidadades/1 or /especialidadades/1.json
  def show
  end

  # GET /especialidadades/new
  def new
    @especialidadade = Especialidadade.new
  end

  # GET /especialidadades/1/edit
  def edit
  end

  # POST /especialidadades or /especialidadades.json
  def create
    @especialidadade = Especialidadade.new(especialidadade_params)

    respond_to do |format|
      if @especialidadade.save
        format.html { redirect_to especialidadade_url(@especialidadade), notice: "Especialidadade was successfully created." }
        format.json { render :show, status: :created, location: @especialidadade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @especialidadade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especialidadades/1 or /especialidadades/1.json
  def update
    respond_to do |format|
      if @especialidadade.update(especialidadade_params)
        format.html { redirect_to especialidadade_url(@especialidadade), notice: "Especialidadade was successfully updated." }
        format.json { render :show, status: :ok, location: @especialidadade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @especialidadade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especialidadades/1 or /especialidadades/1.json
  def destroy
    @especialidadade.destroy

    respond_to do |format|
      format.html { redirect_to especialidadades_url, notice: "Especialidadade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especialidadade
      @especialidadade = Especialidadade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def especialidadade_params
      params.require(:especialidadade).permit(:poder, :tipo)
    end
end

app/controllers/especialidades_controller.rb
class EspecialidadesController < ApplicationController
  before_action :set_especialidade, only: %i[ show edit update destroy ]

  # GET /especialidades or /especialidades.json
  def index
    @especialidades = Especialidade.all
  end

  # GET /especialidades/1 or /especialidades/1.json
  def show
  end

  # GET /especialidades/new
  def new
    @especialidade = Especialidade.new
  end

  # GET /especialidades/1/edit
  def edit
  end

  # POST /especialidades or /especialidades.json
  def create
    @especialidade = Especialidade.new(especialidade_params)

    respond_to do |format|
      if @especialidade.save
        format.html { redirect_to especialidade_url(@especialidade), notice: "Especialidade was successfully created." }
        format.json { render :show, status: :created, location: @especialidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especialidades/1 or /especialidades/1.json
  def update
    respond_to do |format|
      if @especialidade.update(especialidade_params)
        format.html { redirect_to especialidade_url(@especialidade), notice: "Especialidade was successfully updated." }
        format.json { render :show, status: :ok, location: @especialidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especialidades/1 or /especialidades/1.json
  def destroy
    @especialidade.destroy

    respond_to do |format|
      format.html { redirect_to especialidades_url, notice: "Especialidade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especialidade
      @especialidade = Especialidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def especialidade_params
      params.require(:especialidade).permit(:poder, :tipo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
       def locale
        I18n.locale == :en ? "Estados Unidos" : "Português do Brasil"
    end
    
    
    def data_br(data_us)
        data_us.strftime("%d/%m/%Y")
    end
end

app/helpers/cdzs_helper.rb
module CdzsHelper
end

app/helpers/especialidades_helper.rb
module EspecialidadesHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cdzs/_form.html.erb
<%= form_with(model: cdz, local: true) do |form| %>
  <% if cdz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cdz.errors.count, "error") %> prohibited this cdz from being saved:</h2>

      <ul>
      <% cdz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome,class:"form-control", placeholder:"Cavaleiro" %>
  </div>
  

  <div class="form-group">
    <%= form.label :costelação %>
    <%= form.text_field :costelação, class:"form-control", placeholder:"Protetor" %> 
  </div>

  <div class="form-group">
    <%= form.label :idade %>
    <%= form.number_field :idade, class:"form-control", placeholder:"Anos" %> 
  </div>

  <div class="form-group">
    <%= form.label :foto %>
    <%= form.text_field :foto, class:"form-control", placeholder:"http://img.url" %>
    <%#= image_tag cdz.foto, size:"150x150" %> <!--codigo ruby -->
  </div>
  
  <div class="form-group">
    <%= form.label :especialidade_id %>
    <%= form.select("especialidade_id", @especialidade_options, { include_blank: 'Selecione..' }, class:"form-control") %>
    
    
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>


</br>

app/views/cdzs/edit.html.erb
<h1><%= t('editing.cdz') %></h1>

<%= render 'form', cdz: @cdz %>


<%= link_to t('links.show'), @cdz, class:"btn btn-primary" %> 
<%= link_to t('links.back'), cdzs_path, class:"btn btn-primary" %>

app/views/cdzs/index.html.erb
<p id="notice"><%= notice %></p>

DATA: <%= data_br(Date.today) %>

<h1><%= Cdz.model_name.human(count: @cdzs.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= @cdzs.human_attribute_name(:nome)%> </th>
      <th><%= @cdzs.human_attribute_name(:Costelação)%> </th>
      <th><%= @cdzs.human_attribute_name(:Idade)%> </th>
      <th> <%= @cdzs.human_attribute_name(:Foto)%> </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cdzs.each do |cdz| %>
      <tr>
        <td><%= cdz.nome %></td>
        <td><%= cdz.costelação %></td>
        <td><%= cdz.idade %></td>
        <td><%= image_tag cdz.foto, size:"150x150" %></td>
        <td><%= link_to t('links.show'), cdz,  class:"btn btn-primary" %></td>
        <td><%= link_to t('links.edit'), edit_cdz_path(cdz), class:"btn btn-primary" %></td>
        <td><%= link_to t('links.delete'), cdz, method: :delete, data: { confirm: t('messages.confirm'), }, class:"btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.cdz'), new_cdz_path, class:"btn btn-primary" %>

app/views/cdzs/new.html.erb
<h1><%= t('new.cdz') %></h1>

<%= render 'form', cdz: @cdz %>

<%= link_to t('links.back'), cdzs_path, class:"btn btn-primary" %>

app/views/cdzs/show.html.erb
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, @cdz.class.human_attribute_name(:nome) %>
    <%= text_field_tag nil, @cdz.nome, class:"form-control", disabled:true %>
  </div>
  

  <div class="form-group">
    <%= label_tag nil, @cdz.class.human_attribute_name(:costelação) %>
    <%= text_field_tag nil, @cdz.costelação , class:"form-control", disabled:true %>  
  </div>

  <div class="form-group">
    <%= label_tag nil, @cdz.class.human_attribute_name(:idade) %>
    <%= text_field_tag nil, @cdz.idade , class:"form-control", disabled:true   %>
   </div>
   
  <div class="form-group">
    <%= label_tag nil, @cdz.class.human_attribute_name(:foto) %>
    <%= text_field_tag nil, @cdz.foto , class:"form-control", disabled:true %>
   </div>
   
    <div class="form-group">
    <%= label_tag nil, @cdz.class.human_attribute_name(:especialidade) %>
    <%= text_field_tag nil, @cdz.especialidade.tipo , class:"form-control", disabled:true %>
   </div>
   
    


</form>

<%= link_to 'Edit', edit_cdz_path(@cdz),class:"btn btn-primary"  %> |
<%= link_to 'Back', cdzs_path,class:"btn btn-primary"  %>

app/views/especialidades/_form.html.erb
<%= form_with(model: especialidade, local: true) do |form| %>
  <% if especialidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(especialidade.errors.count, "error") %> prohibited this especialidade from being saved:</h2>

      <ul>
      <% especialidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :poder %>
    <%= form.text_field :poder %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

</br>

app/views/especialidades/edit.html.erb
<h1><%= t('Editing.Especialidade') %></h1>

<%= render 'form', especialidade: @especialidade %>

<%= link_to 'Show', @especialidade,  class: "btn btn-primary" %> 
<%= link_to 'Back', especialidades_path,  class: "btn btn-primary" %>

app/views/especialidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= Especialidade.model_name.human(count: @especialidades.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @especialidades.human_attribute_name(:poder)%></th>
      <th><%= @especialidades.human_attribute_name(:Tipos)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @especialidades.each do |especialidade| %>
      <tr>
        <td><%= t('especialidade.poder') %></td>
        <td><%= t('especialidade.tipo') %></td>
        <td><%= link_to t('links.show'), especialidade, class: "btn btn-primary" %></td>
        <td><%= link_to t('links.edit'), edit_especialidade_path(especialidade),  class: "btn btn-primary" %></td>
        <td><%= link_to t('links.destroy'), especialidade, method: :delete, data: { confirm: t('messages.confirm'), },  class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.specialty'), new_especialidade_path, class: "btn btn-primary" %>

app/views/especialidades/new.html.erb
<h1><%= t('new.especialidade') %></h1>

<%= render 'form', especialidade: @especialidade,  class: "btn btn-primary" %>

<%= link_to 'Back', especialidades_path,  class: "btn btn-primary" %>

app/views/especialidades/show.html.erb
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, @especialidade.class.human_attribute_name(:poder) %>
    <%= text_field_tag nil, @especialidade.poder, class:"form-control", disabled:true %>
  </div>
  

  <div class="form-group">
    <%= label_tag nil, @especialidade.class.human_attribute_name(:tipo) %>
    <%= text_field_tag nil, @especialidade.tipo , class:"form-control", disabled:true %>  
  </div>


</form>

<%= link_to 'Edit', edit_especialidade_path(@especialidade), class:"btn btn-primary" %> |
<%= link_to 'Back', especialidades_path, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('cdz')%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  params[:controller], 'data-turbolinks-track': 'reload' %>
    
  </head>

   <body>
    <div class="container-fluid">
      <ul class="nav justify-content-end">
        <li>
          <%= link_to 'HOME', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Português', root_path(locale: 'pt-BR'), class:"nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to 'English', root_path(locale: 'en'), class:"nav-link" %>
        </li>
      </ul>
      
    <%= yield %> <%# index.html.erb, edit.html.erb %>
    </div>
    <script> $.notify("Tudo certo", "success");</script>
    </body>
</html>

app/views/welcome/_menu.html.erb
<%= link_to "#{Cdz.model_name.human}", cdzs_path, class:"btn btn-primary btn-lg" %>

<%= link_to "#{Especialidade.model_name.human}", especialidades_path, class:"btn btn-primary btn-lg" %>
   

app/views/welcome/index.html.erb
<div class="jumbotron">
 <strong> <h1 class="display-4"><%= t('cdz') %></h1>
 <p class="lead"><%= t('messages.welcome') %></p>
  <hr class="my-4">
  <p><%= t('messages.menu') %></p></strong> 

  
  <%= render "menu" %>
</div>